# Site settings
title: C. Cui
email: cuicaihao@gmail.com
description: > All the tips of experience about life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cuicaihao.github.io" # the base hostname & protocol for your site
twitter_username: cuicaihao
github_username:  cuicaihao

# Build settings
markdown: kramdown
